### PR TITLE
Exercise 6

### PR DESCRIPTION
**Pull request by TimWooSoftwire**
Adding in the three diagrams

### CODE REVIEW

**Comment by TimWooSoftwire** [comment]
I'll paste the diagram as images here in case that makes it easier (they're also saved as png in the repo)
Context: 
ContextDiagramTimWoo

**Comment by TimWooSoftwire** [comment]
ContainerDiagramTimWoo

**Comment by TimWooSoftwire** [comment]
ComponentDiagramTimwoo

**Comment by hugh-emerson** [comment]
First two diagrams look great. But the component diagram is wrong:

- You do not have a single page app (SPA). SPA refers to a web app where the server response consists of basic html layout plus a bunch of javascript which then executes in browser to handle fetching data/rendering/navigation/app logic. You should relabel it "webapp logic" or "controller logic" or something instead. And replace "UI presented to user" with something like "Python MVC controller" or "Flask routes"?
- It does not "forward API requests" to trello_helper. It parses HTTP requests and then uses trello_helper to actually fetch/update data. It also creates HTTP responses (sometimes using the data returned by trello_helper, combined with a template).
- I also don't agree with the arrow from trello_helper to templates. trello_helper does not directly interact with the template. Your app uses it to fetch data and then **it** passes that data to the template.

Let me know if have any questions, but you can merge this whenever you're ready.

(PS: nice top hat.)

**Pull request merged**
